.TH "shcodecs-enc" 1 "Oct 2010" "SH Codecs" "Linux-SH Multimedia"

.SH NAME
shcodecs-enc \- Encode raw YCbCr4:2:0 image data to a video Elementary Stream using the SH-Mobile VPU

.SH SYNOPSIS

.B \fBshcodecs-enc\fR \fIcontrol-file\fR \fB...\fR
.PP
\fBshcodecs-enc\fR [\-h | \-\-help ]  [\-v  | \-\-version ]

.SH OPTIONS
.PP
\fBshcodecs-enc\fR accepts the following options:

.SS "Miscellaneous options"
.IP "\-\-help" 10
Display usage information and exit.
.IP "\-v, \-\-version" 10
Output version information and exit.

.SH DESCRIPTION
.B shcodecs-enc
Encode raw YCbCr4:2:0 image data to a video Elementary Stream using the SH-Mobile VPU.
Input on stdin, output on stdout.

.SH AUTHORS

shcodecs-enc was written by Conrad Parker

Please report bugs to <linux-sh@vger.kernel.org>
